spring.application.name=PriceTracker
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/pricetracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:qwerty}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.token = ${TELEGRAM_BOT_TOKEN}
telegram.bot.name = ${BOT_USERNAME:jvpricetracker_bot}
telegram.bot.chatId = ${CHAT_ID:1247124357}
